// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: college_info.sql

package postgres

import (
	"context"
)

const getClasses = `-- name: GetClasses :many
SELECT class_id, classname 
FROM class_info
`

func (q *Queries) GetClasses(ctx context.Context) ([]ClassInfo, error) {
	rows, err := q.db.QueryContext(ctx, getClasses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClassInfo
	for rows.Next() {
		var i ClassInfo
		if err := rows.Scan(&i.ClassID, &i.Classname); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
