// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: division_info.sql

package postgres

import (
	"context"
)

const getDivisions = `-- name: GetDivisions :many
SELECT division_id, division_name, class_id 
FROM division_info
`

func (q *Queries) GetDivisions(ctx context.Context) ([]DivisionInfo, error) {
	rows, err := q.db.QueryContext(ctx, getDivisions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DivisionInfo
	for rows.Next() {
		var i DivisionInfo
		if err := rows.Scan(&i.DivisionID, &i.DivisionName, &i.ClassID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
