// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package postgres

import (
	"time"
)

type AttendanceInfo struct {
	AttendanceID int32
	StudentID    int32
	Date         time.Time
	Status       bool
	ClassID      int32
	DivisionID   int32
}

type ClassInfo struct {
	ClassID   int32
	Classname string
}

type DivisionInfo struct {
	DivisionID   int32
	Divisionname string
	ClassID      int32
}

type StaffCredential struct {
	StaffID      int32
	PasswordHash string
}

type StaffInfo struct {
	ID        int32
	Firstname string
	Lastname  string
	Email     string
	StaffID   int32
}

type StudentCredential struct {
	StudentID    int32
	PasswordHash string
}

type StudentInfo struct {
	ID        int32
	Firstname string
	Lastname  string
	Rollno    int32
	Email     string
	Classname string
	Division  string
	Year      int32
	StudentID int32
}
