// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package postgres

type StaffCredential struct {
	StaffID      int32
	PasswordHash string
}

type Student struct {
	ID        int32
	Firstname string
	Lastname  string
	Rollno    int32
	Email     string
	Classname string
	Division  string
	Year      int32
	StudentID int32
}

type StudentCredential struct {
	StudentID    int32
	PasswordHash string
}
